import './globals.css'
import { Inter } from 'next/font/google'
import { Navbar } from './navbar/Navbar'
import { User } from '@/model/Model'

const inter = Inter({ subsets: ['latin'] })

interface HomeState{
  user: User | undefined
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}, ) {
  return (
    <html lang="en">
      <body className='wrapper'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
